### ISSUE TITLE
Chip delete is not working

### ISSUE THREAD

**Issue by Bockos** [akbarpulatov/flutter_awesome_select#17]
Hi Akbar,

In multiple selection, the selected chips on the body have delete section. But not work even in your example.
Could you check it please?

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by Bockos** [comment]
Hi  @vasilich6107 ,

Issue still remains. 
Please consider the picture below. The delete property in the "S2Tile.fromState > body" section is working but the selected property keep remaining in the screen. I mean it works in backend, but UI does not change. How can I fix that problem? 

When I check your examples, it also occurs in there.

My delete code;
chipOnDelete: (i) {
                            setState(() => groupedBusinessListSelected
                                .remove(state.selected!.choice![i].value));

![image](https://user-images.githubusercontent.com/23163077/141799714-b38310ec-d340-4b88-8ae5-095dd2210844.png)

**Comment by vasilich6107** [comment]
@Bockos please create the issue in corresponding repository
https://github.com/artflutter/flutter_awesome_select/issues

**Comment by akbarpulatov** [comment]
Can you share your code fully?

**Comment by Tristl** [comment]
I have encountrered the same problem and have solved / bypassed it by adding:

`state.selected?.choice?.removeAt(i);` in the function for `chipOnDelete`

**Comment by iqboladahamjonov** [comment]
> I have encountrered the same problem and have solved / bypassed it by adding:
> 
> `state.selected?.choice?.removeAt(i);` in the function for `chipOnDelete`

This is actaully right solution. The respective part in the example can be fixed with `state.selected?.choice?.removeAt(i); ` instead of `_cars?.remove(state.selected?.choice?[i].value); `
